version: 2

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - librsvg2-bin
