var annotated_dup =
[
    [ "auxiliary", null, [
      [ "ForEachType", "structauxiliary_1_1_for_each_type.html", null ],
      [ "ForEachType< Functor >", "structauxiliary_1_1_for_each_type_3_01_functor_01_4.html", null ],
      [ "ForEachType< Functor, FirstType, OtherTypes... >", "structauxiliary_1_1_for_each_type_3_01_functor_00_01_first_type_00_01_other_types_8_8_8_01_4.html", null ]
    ] ],
    [ "detail", null, [
      [ "char_to_explicit_char", "structdetail_1_1char__to__explicit__char.html", null ],
      [ "char_to_explicit_char< false >", "structdetail_1_1char__to__explicit__char_3_01false_01_4.html", null ],
      [ "char_to_explicit_char< true >", "structdetail_1_1char__to__explicit__char_3_01true_01_4.html", null ]
    ] ],
    [ "internal", null, [
      [ "DefineSeriesConstructorPerPathType", "structinternal_1_1_define_series_constructor_per_path_type.html", null ]
    ] ],
    [ "openPMD", "namespaceopen_p_m_d.html", [
      [ "auxiliary", null, [
        [ "detail", null, [
          [ "append_to_variant", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1append__to__variant.html", null ],
          [ "append_to_variant< first_type, std::variant< other_types... > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1append__to__variant_3_01first__type_00_01std_1_1variae25766e8d7b09269965eb1567322252b.html", null ],
          [ "as_shared_pointer", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1as__shared__pointer.html", null ],
          [ "bottom", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1bottom.html", null ],
          [ "IsArray", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_array.html", null ],
          [ "IsArray< std::array< T, n > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_array_3_01std_1_1array_3_01_t_00_01n_01_4_01_4.html", null ],
          [ "IsChar", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_char.html", null ],
          [ "IsChar< char >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_char_3_01char_01_4.html", null ],
          [ "IsChar< signed char >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_char_3_01signed_01char_01_4.html", null ],
          [ "IsChar< unsigned char >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_char_3_01unsigned_01char_01_4.html", null ],
          [ "IsComplex", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_complex.html", null ],
          [ "IsComplex< std::complex< T > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_complex_3_01std_1_1complex_3_01_t_01_4_01_4.html", null ],
          [ "IsPointer", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_pointer.html", null ],
          [ "IsPointer< std::shared_ptr< T > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_pointer_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
          [ "IsPointer< std::unique_ptr< T, Del > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_pointer_3_01std_1_1unique__ptr_3_01_t_00_01_del_01_4_01_4.html", null ],
          [ "IsPointer< T * >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_pointer_3_01_t_01_5_01_4.html", null ],
          [ "IsPointer< UniquePtrWithLambda< T > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_pointer_3_01_unique_ptr_with_lambda_3_01_t_01_4_01_4.html", null ],
          [ "IsVector", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_vector.html", null ],
          [ "IsVector< std::vector< T > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1_is_vector_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ],
          [ "map_variant", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1map__variant.html", null ],
          [ "map_variant< F, std::variant< first_type, other_types... > >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1map__variant_3_01_f_00_01std_1_1variant_3_01first__ty8a03d7babd74ac32800eea511211f97d.html", null ],
          [ "map_variant< F, std::variant<> >", "structopen_p_m_d_1_1auxiliary_1_1detail_1_1map__variant_3_01_f_00_01std_1_1variant_3_4_01_4.html", null ]
        ] ],
        [ "BlockSlicer", "classopen_p_m_d_1_1auxiliary_1_1_block_slicer.html", "classopen_p_m_d_1_1auxiliary_1_1_block_slicer" ],
        [ "CustomDelete", "classopen_p_m_d_1_1auxiliary_1_1_custom_delete.html", null ],
        [ "OneDimensionalBlockSlicer", "classopen_p_m_d_1_1auxiliary_1_1_one_dimensional_block_slicer.html", "classopen_p_m_d_1_1auxiliary_1_1_one_dimensional_block_slicer" ],
        [ "OutOfRangeMsg", "classopen_p_m_d_1_1auxiliary_1_1_out_of_range_msg.html", null ],
        [ "overloaded", "structopen_p_m_d_1_1auxiliary_1_1overloaded.html", null ],
        [ "StringMatrix", "structopen_p_m_d_1_1auxiliary_1_1_string_matrix.html", null ],
        [ "Variant", "classopen_p_m_d_1_1auxiliary_1_1_variant.html", "classopen_p_m_d_1_1auxiliary_1_1_variant" ],
        [ "WriteBuffer", "structopen_p_m_d_1_1auxiliary_1_1_write_buffer.html", "structopen_p_m_d_1_1auxiliary_1_1_write_buffer" ]
      ] ],
      [ "benchmark", null, [
        [ "MemoryProfiler", "classopen_p_m_d_1_1benchmark_1_1_memory_profiler.html", "classopen_p_m_d_1_1benchmark_1_1_memory_profiler" ],
        [ "Timer", "classopen_p_m_d_1_1benchmark_1_1_timer.html", "classopen_p_m_d_1_1benchmark_1_1_timer" ]
      ] ],
      [ "chunk_assignment", null, [
        [ "BinPacking", "structopen_p_m_d_1_1chunk__assignment_1_1_bin_packing.html", "structopen_p_m_d_1_1chunk__assignment_1_1_bin_packing" ],
        [ "Blocks", "structopen_p_m_d_1_1chunk__assignment_1_1_blocks.html", "structopen_p_m_d_1_1chunk__assignment_1_1_blocks" ],
        [ "BlocksOfSourceRanks", "structopen_p_m_d_1_1chunk__assignment_1_1_blocks_of_source_ranks.html", "structopen_p_m_d_1_1chunk__assignment_1_1_blocks_of_source_ranks" ],
        [ "ByCuboidSlice", "structopen_p_m_d_1_1chunk__assignment_1_1_by_cuboid_slice.html", "structopen_p_m_d_1_1chunk__assignment_1_1_by_cuboid_slice" ],
        [ "ByHostname", "structopen_p_m_d_1_1chunk__assignment_1_1_by_hostname.html", "structopen_p_m_d_1_1chunk__assignment_1_1_by_hostname" ],
        [ "DiscardingStrategy", "structopen_p_m_d_1_1chunk__assignment_1_1_discarding_strategy.html", "structopen_p_m_d_1_1chunk__assignment_1_1_discarding_strategy" ],
        [ "FailingStrategy", "structopen_p_m_d_1_1chunk__assignment_1_1_failing_strategy.html", "structopen_p_m_d_1_1chunk__assignment_1_1_failing_strategy" ],
        [ "FromPartialStrategy", "structopen_p_m_d_1_1chunk__assignment_1_1_from_partial_strategy.html", "structopen_p_m_d_1_1chunk__assignment_1_1_from_partial_strategy" ],
        [ "PartialAssignment", "structopen_p_m_d_1_1chunk__assignment_1_1_partial_assignment.html", null ],
        [ "PartialStrategy", "structopen_p_m_d_1_1chunk__assignment_1_1_partial_strategy.html", "structopen_p_m_d_1_1chunk__assignment_1_1_partial_strategy" ],
        [ "RoundRobin", "structopen_p_m_d_1_1chunk__assignment_1_1_round_robin.html", "structopen_p_m_d_1_1chunk__assignment_1_1_round_robin" ],
        [ "RoundRobinOfSourceRanks", "structopen_p_m_d_1_1chunk__assignment_1_1_round_robin_of_source_ranks.html", "structopen_p_m_d_1_1chunk__assignment_1_1_round_robin_of_source_ranks" ],
        [ "Strategy", "structopen_p_m_d_1_1chunk__assignment_1_1_strategy.html", "structopen_p_m_d_1_1chunk__assignment_1_1_strategy" ]
      ] ],
      [ "detail", null, [
        [ "seek_types", null, [
          [ "Next_t", "structopen_p_m_d_1_1detail_1_1seek__types_1_1_next__t.html", null ],
          [ "Seek_Iteration_t", "structopen_p_m_d_1_1detail_1_1seek__types_1_1_seek___iteration__t.html", null ]
        ] ],
        [ "step_status_types", null, [
          [ "After_t", "structopen_p_m_d_1_1detail_1_1step__status__types_1_1_after__t.html", null ],
          [ "Before_t", "structopen_p_m_d_1_1detail_1_1step__status__types_1_1_before__t.html", null ],
          [ "During_t", "structopen_p_m_d_1_1detail_1_1step__status__types_1_1_during__t.html", null ]
        ] ],
        [ "ADIOS2File", "classopen_p_m_d_1_1detail_1_1_a_d_i_o_s2_file.html", "classopen_p_m_d_1_1detail_1_1_a_d_i_o_s2_file" ],
        [ "AdiosAttributes", "structopen_p_m_d_1_1detail_1_1_adios_attributes.html", "structopen_p_m_d_1_1detail_1_1_adios_attributes" ],
        [ "AdiosVariables", "structopen_p_m_d_1_1detail_1_1_adios_variables.html", "structopen_p_m_d_1_1detail_1_1_adios_variables" ],
        [ "AttributeInfo", "structopen_p_m_d_1_1detail_1_1_attribute_info.html", null ],
        [ "AttributeReader", "structopen_p_m_d_1_1detail_1_1_attribute_reader.html", "structopen_p_m_d_1_1detail_1_1_attribute_reader" ],
        [ "AttributeTypes", "structopen_p_m_d_1_1detail_1_1_attribute_types.html", null ],
        [ "AttributeTypes< bool >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01bool_01_4.html", null ],
        [ "AttributeTypes< std::array< T, n > >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01std_1_1array_3_01_t_00_01n_01_4_01_4.html", null ],
        [ "AttributeTypes< std::complex< long double > >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01std_1_1complex_3_01long_01double_01_4_01_4.html", null ],
        [ "AttributeTypes< std::vector< std::complex< long double > > >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01std_1_1vector_3_01std_1_1complex_3_01long_01double_01_4_01_4_01_4.html", null ],
        [ "AttributeTypes< std::vector< std::string > >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01std_1_1vector_3_01std_1_1string_01_4_01_4.html", null ],
        [ "AttributeTypes< std::vector< T > >", "structopen_p_m_d_1_1detail_1_1_attribute_types_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ],
        [ "AttributeWithShape", "structopen_p_m_d_1_1detail_1_1_attribute_with_shape.html", null ],
        [ "AttributeWithShapeAndResource", "structopen_p_m_d_1_1detail_1_1_attribute_with_shape_and_resource.html", null ],
        [ "AttributeWriter", "structopen_p_m_d_1_1detail_1_1_attribute_writer.html", null ],
        [ "BasicDatatype", "structopen_p_m_d_1_1detail_1_1_basic_datatype.html", null ],
        [ "BufferedAction", "structopen_p_m_d_1_1detail_1_1_buffered_action.html", null ],
        [ "BufferedGet", "structopen_p_m_d_1_1detail_1_1_buffered_get.html", null ],
        [ "BufferedPut", "structopen_p_m_d_1_1detail_1_1_buffered_put.html", null ],
        [ "BufferedUniquePtrPut", "structopen_p_m_d_1_1detail_1_1_buffered_unique_ptr_put.html", null ],
        [ "CurrentStep", "structopen_p_m_d_1_1detail_1_1_current_step.html", null ],
        [ "DatasetExtender", "structopen_p_m_d_1_1detail_1_1_dataset_extender.html", null ],
        [ "DatasetHelper", "structopen_p_m_d_1_1detail_1_1_dataset_helper.html", null ],
        [ "DatasetOpener", "structopen_p_m_d_1_1detail_1_1_dataset_opener.html", null ],
        [ "DatasetReader", "structopen_p_m_d_1_1detail_1_1_dataset_reader.html", null ],
        [ "DatasetTypes", "structopen_p_m_d_1_1detail_1_1_dataset_types.html", null ],
        [ "DefaultValue", "structopen_p_m_d_1_1detail_1_1_default_value.html", null ],
        [ "do_convert", "structopen_p_m_d_1_1detail_1_1do__convert.html", null ],
        [ "GetSpan", "structopen_p_m_d_1_1detail_1_1_get_span.html", null ],
        [ "HasOperators", "structopen_p_m_d_1_1detail_1_1_has_operators.html", null ],
        [ "I_UpdateSpan", "structopen_p_m_d_1_1detail_1_1_i___update_span.html", null ],
        [ "MakeEmpty", "structopen_p_m_d_1_1detail_1_1_make_empty.html", null ],
        [ "PreloadAdiosAttributes", "classopen_p_m_d_1_1detail_1_1_preload_adios_attributes.html", "classopen_p_m_d_1_1detail_1_1_preload_adios_attributes" ],
        [ "RetrieveBlocksInfo", "structopen_p_m_d_1_1detail_1_1_retrieve_blocks_info.html", null ],
        [ "RunUniquePtrPut", "structopen_p_m_d_1_1detail_1_1_run_unique_ptr_put.html", null ],
        [ "Seek", "structopen_p_m_d_1_1detail_1_1_seek.html", null ],
        [ "to_vector_type", "structopen_p_m_d_1_1detail_1_1to__vector__type.html", null ],
        [ "ToDatatype", "structopen_p_m_d_1_1detail_1_1_to_datatype.html", null ],
        [ "ToDatatypeHelper", "structopen_p_m_d_1_1detail_1_1_to_datatype_helper.html", null ],
        [ "ToDatatypeHelper< bool >", "structopen_p_m_d_1_1detail_1_1_to_datatype_helper_3_01bool_01_4.html", null ],
        [ "ToDatatypeHelper< std::array< T, n > >", "structopen_p_m_d_1_1detail_1_1_to_datatype_helper_3_01std_1_1array_3_01_t_00_01n_01_4_01_4.html", null ],
        [ "ToDatatypeHelper< std::vector< T > >", "structopen_p_m_d_1_1detail_1_1_to_datatype_helper_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ],
        [ "ToVectorType", "structopen_p_m_d_1_1detail_1_1_to_vector_type.html", null ],
        [ "UpdateSpan", "structopen_p_m_d_1_1detail_1_1_update_span.html", null ],
        [ "VariableDefiner", "structopen_p_m_d_1_1detail_1_1_variable_definer.html", null ],
        [ "WriteDataset", "structopen_p_m_d_1_1detail_1_1_write_dataset.html", null ]
      ] ],
      [ "error", null, [
        [ "BackendConfigSchema", "classopen_p_m_d_1_1error_1_1_backend_config_schema.html", null ],
        [ "IllegalInOpenPMDStandard", "classopen_p_m_d_1_1error_1_1_illegal_in_open_p_m_d_standard.html", null ],
        [ "Internal", "classopen_p_m_d_1_1error_1_1_internal.html", null ],
        [ "NoSuchAttribute", "classopen_p_m_d_1_1error_1_1_no_such_attribute.html", null ],
        [ "OperationUnsupportedInBackend", "classopen_p_m_d_1_1error_1_1_operation_unsupported_in_backend.html", null ],
        [ "ReadError", "classopen_p_m_d_1_1error_1_1_read_error.html", null ],
        [ "WrongAPIUsage", "classopen_p_m_d_1_1error_1_1_wrong_a_p_i_usage.html", null ]
      ] ],
      [ "internal", null, [
        [ "BeginStepTypes", null, [
          [ "BeginStepRandomAccess", "structopen_p_m_d_1_1internal_1_1_begin_step_types_1_1_begin_step_random_access.html", null ],
          [ "BeginStepSequentially", "structopen_p_m_d_1_1internal_1_1_begin_step_types_1_1_begin_step_sequentially.html", null ],
          [ "DontBeginStep", "structopen_p_m_d_1_1internal_1_1_begin_step_types_1_1_dont_begin_step.html", null ]
        ] ],
        [ "AttributableData", "classopen_p_m_d_1_1internal_1_1_attributable_data.html", null ],
        [ "BaseRecordComponentData", "classopen_p_m_d_1_1internal_1_1_base_record_component_data.html", "classopen_p_m_d_1_1internal_1_1_base_record_component_data" ],
        [ "BaseRecordData", "classopen_p_m_d_1_1internal_1_1_base_record_data.html", null ],
        [ "ContainerData", "classopen_p_m_d_1_1internal_1_1_container_data.html", "classopen_p_m_d_1_1internal_1_1_container_data" ],
        [ "DeferredParseAccess", "structopen_p_m_d_1_1internal_1_1_deferred_parse_access.html", "structopen_p_m_d_1_1internal_1_1_deferred_parse_access" ],
        [ "EraseStaleEntries", "classopen_p_m_d_1_1internal_1_1_erase_stale_entries.html", "classopen_p_m_d_1_1internal_1_1_erase_stale_entries" ],
        [ "FlushParams", "structopen_p_m_d_1_1internal_1_1_flush_params.html", null ],
        [ "HomogenizeExtents", "structopen_p_m_d_1_1internal_1_1_homogenize_extents.html", null ],
        [ "IterationData", "classopen_p_m_d_1_1internal_1_1_iteration_data.html", "classopen_p_m_d_1_1internal_1_1_iteration_data" ],
        [ "ParsedFlushParams", "structopen_p_m_d_1_1internal_1_1_parsed_flush_params.html", null ],
        [ "RecordComponentData", "classopen_p_m_d_1_1internal_1_1_record_component_data.html", "classopen_p_m_d_1_1internal_1_1_record_component_data" ],
        [ "ScalarIterator", "classopen_p_m_d_1_1internal_1_1_scalar_iterator.html", "classopen_p_m_d_1_1internal_1_1_scalar_iterator" ],
        [ "SeriesData", "classopen_p_m_d_1_1internal_1_1_series_data.html", "classopen_p_m_d_1_1internal_1_1_series_data" ],
        [ "SharedAttributableData", "classopen_p_m_d_1_1internal_1_1_shared_attributable_data.html", "classopen_p_m_d_1_1internal_1_1_shared_attributable_data" ]
      ] ],
      [ "json", null, [
        [ "JsonMatcher", "classopen_p_m_d_1_1json_1_1_json_matcher.html", "classopen_p_m_d_1_1json_1_1_json_matcher" ],
        [ "MatcherPerBackend", "classopen_p_m_d_1_1json_1_1_matcher_per_backend.html", "classopen_p_m_d_1_1json_1_1_matcher_per_backend" ],
        [ "ParsedConfig", "structopen_p_m_d_1_1json_1_1_parsed_config.html", null ],
        [ "Pattern", "structopen_p_m_d_1_1json_1_1_pattern.html", null ],
        [ "TracingJSON", "classopen_p_m_d_1_1json_1_1_tracing_j_s_o_n.html", "classopen_p_m_d_1_1json_1_1_tracing_j_s_o_n" ]
      ] ],
      [ "traits", null, [
        [ "GenerationPolicy", "structopen_p_m_d_1_1traits_1_1_generation_policy.html", null ],
        [ "GenerationPolicy< ParticleSpecies >", "structopen_p_m_d_1_1traits_1_1_generation_policy_3_01_particle_species_01_4.html", null ]
      ] ],
      [ "AbstractFilePosition", "classopen_p_m_d_1_1_abstract_file_position.html", null ],
      [ "AbstractIOHandler", "classopen_p_m_d_1_1_abstract_i_o_handler.html", "classopen_p_m_d_1_1_abstract_i_o_handler" ],
      [ "AbstractIOHandlerImpl", "classopen_p_m_d_1_1_abstract_i_o_handler_impl.html", "classopen_p_m_d_1_1_abstract_i_o_handler_impl" ],
      [ "AbstractIOHandlerImplCommon", "classopen_p_m_d_1_1_abstract_i_o_handler_impl_common.html", "classopen_p_m_d_1_1_abstract_i_o_handler_impl_common" ],
      [ "AbstractParameter", "structopen_p_m_d_1_1_abstract_parameter.html", "structopen_p_m_d_1_1_abstract_parameter" ],
      [ "AbstractSeriesIterator", "classopen_p_m_d_1_1_abstract_series_iterator.html", null ],
      [ "AbstractSnapshotsContainer", "classopen_p_m_d_1_1_abstract_snapshots_container.html", null ],
      [ "ADIOS2FilePosition", "structopen_p_m_d_1_1_a_d_i_o_s2_file_position.html", "structopen_p_m_d_1_1_a_d_i_o_s2_file_position" ],
      [ "ADIOS2IOHandler", "classopen_p_m_d_1_1_a_d_i_o_s2_i_o_handler.html", "classopen_p_m_d_1_1_a_d_i_o_s2_i_o_handler" ],
      [ "ADIOS2IOHandlerImpl", "classopen_p_m_d_1_1_a_d_i_o_s2_i_o_handler_impl.html", "classopen_p_m_d_1_1_a_d_i_o_s2_i_o_handler_impl" ],
      [ "Attributable", "classopen_p_m_d_1_1_attributable.html", "classopen_p_m_d_1_1_attributable" ],
      [ "Attribute", "classopen_p_m_d_1_1_attribute.html", "classopen_p_m_d_1_1_attribute" ],
      [ "BaseRecord", "classopen_p_m_d_1_1_base_record.html", "classopen_p_m_d_1_1_base_record" ],
      [ "BaseRecordComponent", "classopen_p_m_d_1_1_base_record_component.html", "classopen_p_m_d_1_1_base_record_component" ],
      [ "BlockSlicer", "classopen_p_m_d_1_1_block_slicer.html", "classopen_p_m_d_1_1_block_slicer" ],
      [ "ChunkInfo", "structopen_p_m_d_1_1_chunk_info.html", "structopen_p_m_d_1_1_chunk_info" ],
      [ "Container", "classopen_p_m_d_1_1_container.html", "classopen_p_m_d_1_1_container" ],
      [ "Dataset", "classopen_p_m_d_1_1_dataset.html", "classopen_p_m_d_1_1_dataset" ],
      [ "DatasetFiller", "classopen_p_m_d_1_1_dataset_filler.html", "classopen_p_m_d_1_1_dataset_filler" ],
      [ "decay_equiv", "structopen_p_m_d_1_1decay__equiv.html", null ],
      [ "DeferredParseAccess", "structopen_p_m_d_1_1_deferred_parse_access.html", "structopen_p_m_d_1_1_deferred_parse_access" ],
      [ "DummyIOHandler", "classopen_p_m_d_1_1_dummy_i_o_handler.html", "classopen_p_m_d_1_1_dummy_i_o_handler" ],
      [ "DynamicMemoryView", "classopen_p_m_d_1_1_dynamic_memory_view.html", "classopen_p_m_d_1_1_dynamic_memory_view" ],
      [ "DynamicSeriesIterator", "classopen_p_m_d_1_1_dynamic_series_iterator.html", null ],
      [ "Error", "classopen_p_m_d_1_1_error.html", null ],
      [ "File", "structopen_p_m_d_1_1_file.html", "structopen_p_m_d_1_1_file" ],
      [ "GetH5DataType", "structopen_p_m_d_1_1_get_h5_data_type.html", null ],
      [ "HDF5FilePosition", "structopen_p_m_d_1_1_h_d_f5_file_position.html", null ],
      [ "HDF5IOHandler", "classopen_p_m_d_1_1_h_d_f5_i_o_handler.html", "classopen_p_m_d_1_1_h_d_f5_i_o_handler" ],
      [ "HDF5IOHandlerImpl", "classopen_p_m_d_1_1_h_d_f5_i_o_handler_impl.html", "classopen_p_m_d_1_1_h_d_f5_i_o_handler_impl" ],
      [ "IndexedIteration", "classopen_p_m_d_1_1_indexed_iteration.html", null ],
      [ "InvalidatableFile", "structopen_p_m_d_1_1_invalidatable_file.html", "structopen_p_m_d_1_1_invalidatable_file" ],
      [ "IOTask", "classopen_p_m_d_1_1_i_o_task.html", "classopen_p_m_d_1_1_i_o_task" ],
      [ "Iteration", "classopen_p_m_d_1_1_iteration.html", "classopen_p_m_d_1_1_iteration" ],
      [ "JSONFilePosition", "structopen_p_m_d_1_1_j_s_o_n_file_position.html", null ],
      [ "JSONIOHandler", "classopen_p_m_d_1_1_j_s_o_n_i_o_handler.html", "classopen_p_m_d_1_1_j_s_o_n_i_o_handler" ],
      [ "JSONIOHandlerImpl", "classopen_p_m_d_1_1_j_s_o_n_i_o_handler_impl.html", "classopen_p_m_d_1_1_j_s_o_n_i_o_handler_impl" ],
      [ "LegacyIteratorAdaptor", "classopen_p_m_d_1_1_legacy_iterator_adaptor.html", null ],
      [ "Mesh", "classopen_p_m_d_1_1_mesh.html", "classopen_p_m_d_1_1_mesh" ],
      [ "MeshRecordComponent", "classopen_p_m_d_1_1_mesh_record_component.html", "classopen_p_m_d_1_1_mesh_record_component" ],
      [ "MPIBenchmark", "classopen_p_m_d_1_1_m_p_i_benchmark.html", "classopen_p_m_d_1_1_m_p_i_benchmark" ],
      [ "MPIBenchmarkReport", "structopen_p_m_d_1_1_m_p_i_benchmark_report.html", "structopen_p_m_d_1_1_m_p_i_benchmark_report" ],
      [ "OneDimensionalBlockSlicer", "classopen_p_m_d_1_1_one_dimensional_block_slicer.html", "classopen_p_m_d_1_1_one_dimensional_block_slicer" ],
      [ "OpaqueSeriesIterator", "classopen_p_m_d_1_1_opaque_series_iterator.html", "classopen_p_m_d_1_1_opaque_series_iterator" ],
      [ "ParallelHDF5IOHandler", "classopen_p_m_d_1_1_parallel_h_d_f5_i_o_handler.html", "classopen_p_m_d_1_1_parallel_h_d_f5_i_o_handler" ],
      [ "ParallelHDF5IOHandlerImpl", "classopen_p_m_d_1_1_parallel_h_d_f5_i_o_handler_impl.html", null ],
      [ "Parameter", "structopen_p_m_d_1_1_parameter.html", null ],
      [ "Parameter< Operation::ADVANCE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_a_d_v_a_n_c_e_01_4.html", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_a_d_v_a_n_c_e_01_4" ],
      [ "Parameter< Operation::AVAILABLE_CHUNKS >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_a_v_a_i_l_a_b_l_e___c_h_u_n_k_s_01_4.html", null ],
      [ "Parameter< Operation::CHECK_FILE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_h_e_c_k___f_i_l_e_01_4.html", null ],
      [ "Parameter< Operation::CLOSE_FILE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_l_o_s_e___f_i_l_e_01_4.html", null ],
      [ "Parameter< Operation::CLOSE_PATH >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_l_o_s_e___p_a_t_h_01_4.html", null ],
      [ "Parameter< Operation::CREATE_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_r_e_a_t_e___d_a_t_a_s_e_t_01_4.html", null ],
      [ "Parameter< Operation::CREATE_FILE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_r_e_a_t_e___f_i_l_e_01_4.html", null ],
      [ "Parameter< Operation::CREATE_PATH >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_c_r_e_a_t_e___p_a_t_h_01_4.html", null ],
      [ "Parameter< Operation::DELETE_ATT >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_d_e_l_e_t_e___a_t_t_01_4.html", null ],
      [ "Parameter< Operation::DELETE_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_d_e_l_e_t_e___d_a_t_a_s_e_t_01_4.html", null ],
      [ "Parameter< Operation::DELETE_FILE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_d_e_l_e_t_e___f_i_l_e_01_4.html", null ],
      [ "Parameter< Operation::DELETE_PATH >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_d_e_l_e_t_e___p_a_t_h_01_4.html", null ],
      [ "Parameter< Operation::DEREGISTER >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_d_e_r_e_g_i_s_t_e_r_01_4.html", null ],
      [ "Parameter< Operation::EXTEND_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_e_x_t_e_n_d___d_a_t_a_s_e_t_01_4.html", null ],
      [ "Parameter< Operation::LIST_ATTS >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_l_i_s_t___a_t_t_s_01_4.html", null ],
      [ "Parameter< Operation::LIST_DATASETS >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_l_i_s_t___d_a_t_a_s_e_t_s_01_4.html", null ],
      [ "Parameter< Operation::LIST_PATHS >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_l_i_s_t___p_a_t_h_s_01_4.html", null ],
      [ "Parameter< Operation::OPEN_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_o_p_e_n___d_a_t_a_s_e_t_01_4.html", null ],
      [ "Parameter< Operation::OPEN_FILE >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_o_p_e_n___f_i_l_e_01_4.html", null ],
      [ "Parameter< Operation::OPEN_PATH >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_o_p_e_n___p_a_t_h_01_4.html", null ],
      [ "Parameter< Operation::READ_ATT >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_r_e_a_d___a_t_t_01_4.html", null ],
      [ "Parameter< Operation::READ_ATT_ALLSTEPS >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_r_e_a_d___a_t_t___a_l_l_s_t_e_p_s_01_4.html", null ],
      [ "Parameter< Operation::READ_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_r_e_a_d___d_a_t_a_s_e_t_01_4.html", null ],
      [ "Parameter< Operation::SET_WRITTEN >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_s_e_t___w_r_i_t_t_e_n_01_4.html", null ],
      [ "Parameter< Operation::TOUCH >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_t_o_u_c_h_01_4.html", null ],
      [ "Parameter< Operation::WRITE_ATT >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_w_r_i_t_e___a_t_t_01_4.html", null ],
      [ "Parameter< Operation::WRITE_DATASET >", "structopen_p_m_d_1_1_parameter_3_01_operation_1_1_w_r_i_t_e___d_a_t_a_s_e_t_01_4.html", null ],
      [ "ParticlePatches", "classopen_p_m_d_1_1_particle_patches.html", null ],
      [ "ParticleSpecies", "classopen_p_m_d_1_1_particle_species.html", null ],
      [ "PatchRecord", "classopen_p_m_d_1_1_patch_record.html", null ],
      [ "PatchRecordComponent", "classopen_p_m_d_1_1_patch_record_component.html", "classopen_p_m_d_1_1_patch_record_component" ],
      [ "RandomAccessIterator", "classopen_p_m_d_1_1_random_access_iterator.html", null ],
      [ "RandomAccessIteratorContainer", "classopen_p_m_d_1_1_random_access_iterator_container.html", null ],
      [ "RandomDatasetFiller", "classopen_p_m_d_1_1_random_dataset_filler.html", "classopen_p_m_d_1_1_random_dataset_filler" ],
      [ "ReadIterations", "classopen_p_m_d_1_1_read_iterations.html", null ],
      [ "Record", "classopen_p_m_d_1_1_record.html", null ],
      [ "RecordComponent", "classopen_p_m_d_1_1_record_component.html", "classopen_p_m_d_1_1_record_component" ],
      [ "Series", "classopen_p_m_d_1_1_series.html", "classopen_p_m_d_1_1_series" ],
      [ "SimpleDatasetFillerProvider", "classopen_p_m_d_1_1_simple_dataset_filler_provider.html", null ],
      [ "Snapshots", "classopen_p_m_d_1_1_snapshots.html", "classopen_p_m_d_1_1_snapshots" ],
      [ "Span", "classopen_p_m_d_1_1_span.html", null ],
      [ "StatefulIterator", "classopen_p_m_d_1_1_stateful_iterator.html", "classopen_p_m_d_1_1_stateful_iterator" ],
      [ "StatefulSnapshotsContainer", "classopen_p_m_d_1_1_stateful_snapshots_container.html", null ],
      [ "UniquePtrWithLambda", "classopen_p_m_d_1_1_unique_ptr_with_lambda.html", "classopen_p_m_d_1_1_unique_ptr_with_lambda" ],
      [ "Writable", "classopen_p_m_d_1_1_writable.html", "classopen_p_m_d_1_1_writable" ],
      [ "WrittenChunkInfo", "structopen_p_m_d_1_1_written_chunk_info.html", "structopen_p_m_d_1_1_written_chunk_info" ]
    ] ],
    [ "openpmd_api", null, [
      [ "DaskArray", "namespaceopenpmd__api_1_1_dask_array.html", [
        [ "DaskRecordComponent", "classopenpmd__api_1_1_dask_array_1_1_dask_record_component.html", "classopenpmd__api_1_1_dask_array_1_1_dask_record_component" ]
      ] ],
      [ "pipe", null, [
        [ "__main__", "namespaceopenpmd__api_1_1pipe_1_1____main____.html", [
          [ "deferred_load", "classopenpmd__api_1_1pipe_1_1____main_____1_1deferred__load.html", null ],
          [ "FallbackMPICommunicator", "classopenpmd__api_1_1pipe_1_1____main_____1_1_fallback_m_p_i_communicator.html", null ],
          [ "IncreaseGranularity", "classopenpmd__api_1_1pipe_1_1____main_____1_1_increase_granularity.html", null ],
          [ "LoadAll", "classopenpmd__api_1_1pipe_1_1____main_____1_1_load_all.html", null ],
          [ "LoadOne", "classopenpmd__api_1_1pipe_1_1____main_____1_1_load_one.html", null ],
          [ "MergingStrategy", "classopenpmd__api_1_1pipe_1_1____main_____1_1_merging_strategy.html", null ],
          [ "pipe", "classopenpmd__api_1_1pipe_1_1____main_____1_1pipe.html", null ]
        ] ]
      ] ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< openPMD::File >", "structstd_1_1hash_3_01open_p_m_d_1_1_file_01_4.html", null ],
      [ "hash< openPMD::InvalidatableFile >", "structstd_1_1hash_3_01open_p_m_d_1_1_invalidatable_file_01_4.html", null ]
    ] ],
    [ "ClonableTrampoline", "struct_clonable_trampoline.html", null ],
    [ "openPMD_PyMPICommObject", "structopen_p_m_d___py_m_p_i_comm_object.html", null ],
    [ "py_object_to_mpi_comm_error", "structpy__object__to__mpi__comm__error.html", null ],
    [ "PyPartialStrategy", "struct_py_partial_strategy.html", "struct_py_partial_strategy" ],
    [ "PyStrategy", "struct_py_strategy.html", "struct_py_strategy" ],
    [ "PythonDynamicMemoryView", "struct_python_dynamic_memory_view.html", null ],
    [ "SetAttributeFromObject", "struct_set_attribute_from_object.html", null ],
    [ "StatefulIteratorPythonAdaptor", "struct_stateful_iterator_python_adaptor.html", null ]
];