packages:
  perl:
    version: [5.14.0, 5.18.2, 5.22.4, 5.26.2]
    paths:
      perl@5.14.0%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /usr
      perl@5.14.0%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /usr
      perl@5.14.0%gcc@6.5.0 arch=linux-ubuntu14-x86_64: /usr
      perl@5.14.0%gcc@7.4.0 arch=linux-ubuntu14-x86_64: /usr
      perl@5.22.4%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /usr
      perl@5.26.2%gcc@9.3.0 arch=linux-ubuntu18-x86_64: /usr
      perl@5.22.4%clang@5.0.0 arch=linux-ubuntu16-x86_64: /usr
      perl@5.22.4%clang@6.0.0 arch=linux-ubuntu16-x86_64: /usr
      perl@5.22.4%clang@7.0.0 arch=linux-ubuntu16-x86_64: /usr
      perl@5.26.1%clang@8.0.0 arch=linux-ubuntu18-x86_64: /usr
      perl@5.18.2%clang@9.1.0 arch=darwin-highsierra-x86_64: /usr
      perl@5.18.2%clang@10.0.0 arch=darwin-highsierra-x86_64: /usr
      perl@5.18.2%clang@11.0.0 arch=darwin-mojave-x86_64: /usr
    buildable: False
  cmake:
    version: [3.11.0]
    paths:
      cmake@3.11.0%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@6.5.0 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@7.4.0 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@9.3.0 arch=linux-ubuntu18-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@5.0.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@6.0.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@7.0.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@8.0.0 arch=linux-ubuntu18-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@9.1.0 arch=darwin-highsierra-x86_64: /Applications/CMake.app/Contents/
      cmake@3.11.0%clang@10.0.0 arch=darwin-highsierra-x86_64: /Applications/CMake.app/Contents/
      cmake@3.11.0%clang@11.0.0 arch=darwin-mojave-x86_64: /Applications/CMake.app/Contents/
    buildable: False
  openmpi:
    version: [1.6.5, 1.10.2, 2.1.1]
    paths:
      openmpi@1.6.5%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@6.5.0 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@7.4.0 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.10.2%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /usr
      openmpi@2.1.1%gcc@9.3.0 arch=linux-ubuntu18-x86_64: /usr
      openmpi@1.10.2%clang@5.0.0 arch=linux-ubuntu16-x86_64: /usr
      openmpi@1.10.2%clang@7.0.0 arch=linux-ubuntu16-x86_64: /usr
    buildable: False
  mpich:
    version: [3.3]
    paths:
      mpich@3.3%clang@8.0.0 arch=linux-ubuntu18-x86_64: /usr
    buildable: False
  hdf5:
    version: [1.10.1, 1.8.13]
  adios:
    variants: ~zfp ~sz ~lz4 ~blosc
  adios2:
    variants: ~zfp ~sz ~png ~dataman ~python ~fortran ~ssc
  python:
    version: [3.5.5, 3.6.3, 3.7.1, 3.7.2, 3.8.0]
    paths:
      python@3.8.0%clang@8.0.0 arch=linux-ubuntu18-x86_64: /home/travis/virtualenv/python3.8
      python@3.8.0%clang@7.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.8
      python@3.7.1%clang@7.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.7
      python@3.6.3%clang@6.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.6
      python@3.6.3%clang@5.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.6
      python@3.8.0%gcc@9.3.0 arch=linux-ubuntu18-x86_64: /home/travis/virtualenv/python3.8
      python@3.6.3%gcc@7.4.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.6
      python@3.5.5%gcc@6.5.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.5
      python@3.6.3%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.6
      python@3.5.5%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.5
      python@3.6.3%gcc@6.5.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.6
      python@3.7.1%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.7
      python@3.7.2%clang@9.1.0 arch=darwin-highsierra-x86_64: /usr/local/opt/python
      python@3.7.2%clang@10.0.0 arch=darwin-highsierra-x86_64: /usr/local/opt/python
      python@3.7.2%clang@11.0.0 arch=darwin-mojave-x86_64: /usr/local/opt/python
    buildable: False

  # speed up builds of dependencies
  ncurses:
    variants: ~termlib          
  gettext:
    variants: ~curses ~libxml2 ~git ~tar ~bzip2 ~xz
  py-numpy:
    variants: ~blas ~lapack

  # set generic binary generation, mpi providers and compiler versions
  all:
    target: ['x86_64']
    providers:
      mpi: [openmpi, mpich]
    compiler: [clang@5.0.0, clang@6.0.0, clang@7.0.0, clang@8.0.0, clang@9.1.0, clang@10.0.0, clang@11.0.0, gcc@4.8.5, gcc@4.9.4, gcc@6.5.0, gcc@7.4.0, gcc@8.1.0, gcc@9.3.0]
