#!/usr/bin/env bash
#
# Copyright 2020-2021 Axel Huebl
#
# License: LGPLv3+

# search recursive inside a folder if a file contains tabs
#
# @result 0 if no files are found, else 1
#

set -eu -o pipefail

cd docs

# treat all warnings as errors
echo "WARN_AS_ERROR = YES" >> Doxyfile

doxygen
