# This is a Spack environment file.
#
# Activating and installing this environment will provide all dependencies
# that are needed for full-feature development.
#   https//spack.readthedocs.io/en/latest/environments.html#anonymous-environments
#
spack:
  specs:
  - hdf5

  packages:
    all:
      target: [x86_64]
      variants: ~mpi ~fortran
      compiler: [clang@6.0.0]

  compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cxxflags: -stdlib=libc++
        ldflags: -stdlib=libc++
      modules: []
      operating_system: ubuntu18.04
      paths:
        cc: /usr/lib/llvm-6.0/bin/clang
        cxx: /usr/lib/llvm-6.0/bin/clang++
        f77: null
        fc: null
      spec: clang@6.0.0
      target: x86_64

  config:
    build_jobs: 2

  mirrors:
    E4S: https://cache.e4s.io
