version: 2

jobs:
  linux-aarch64:
    working_directory: ~/linux-aarch64-wheels
    machine:
      image: ubuntu-2204:current
    # resource_class is what tells CircleCI to use an ARM worker for native arm builds
    #   https://circleci.com/product/features/resource-classes/
    #   https://circleci.com/docs/using-arm/
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            sudo apt update
            sudo apt install cmake g++ gfortran libfabric-dev libopenmpi-dev libhdf5-openmpi-dev hdf5-tools pkgconf python3 python3-setuptools
            sudo .github/workflows/dependencies/install_spack
            python3 -m pip install -U pip
            python3 -m pip install -U packaging setuptools wheel
            python3 -m pip install -U six
            python3 -m pip install -U numpy
            python3 -m pip install -U mpi4py
            python3 -m pip install -U pandas
            python3 -m pip install -U dask
            python3 -m pip install -U pyarrow

            eval $(spack env activate --sh .github/ci/spack-envs/gcc_py_ompi_h5_ad2_arm64/)
            spack install

            share/openPMD/download_samples.sh build
      - run:
          name: Build openPMD-api
          command: |
            eval $(spack env activate --sh .github/ci/spack-envs/gcc_py_ompi_h5_ad2_arm64/)

            export CXXFLAGS="-DPYBIND11_DETAILED_ERROR_MESSAGES=1"

            cmake -S . -B build \
              -DopenPMD_USE_PYTHON=ON \
              -DopenPMD_USE_MPI=ON    \
              -DopenPMD_USE_HDF5=ON   \
              -DopenPMD_USE_ADIOS2=ON \
              -DopenPMD_USE_INVASIVE_TESTS=ON \
              -DPython_EXECUTABLE=$(which python3)
            cmake --build build --parallel 4
      - run:
          name: Test openPMD-api
          command: |
            eval $(spack env activate --sh .github/ci/spack-envs/gcc_py_ompi_h5_ad2_arm64/)
            ctest --test-dir build --output-on-failure

workflows:
  version: 2
  all-tests:
    jobs:
      - linux-aarch64
