# This is a Spack environment file.
#
# Activating and installing this environment will provide all dependencies
# that are needed for full-feature development.
#   https//spack.readthedocs.io/en/latest/environments.html#anonymous-environments
#
spack:
  specs:
  - adios2@2.10
  - hdf5
  - mpich

  packages:
    adios2:
      variants: ~zfp ~sz ~png ~dataman ~python ~fortran ~ssc ~shared ~bzip2 ~blosc2 ~mgard
    cmake:
      externals:
      - spec: cmake@3.31.5
        prefix: /usr
      buildable: False
    mpich:
      externals:
      - spec: mpich@4.0.3
        prefix: /usr
      buildable: False
    perl:
      externals:
      - spec: perl@5.34.0
        prefix: /usr
      buildable: False
    python:
      externals:
      - spec: python@3.10.12
        prefix: /usr
      buildable: False
    all:
      target: [x86_64]
      variants: ~fortran
      providers:
        mpi: [mpich]
      compiler: [clang@12.0.1]

  compilers:
  - compiler:
      environment: {MPICH_CC: /usr/lib/llvm-12/bin/clang, MPICH_CXX: /usr/lib/llvm-12/bin/clang++}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: ubuntu22.04
      paths:
        cc: /usr/bin/mpicc
        cxx: /usr/bin/mpic++
        f77: /usr/bin/mpif77
        fc: /usr/bin/mpifort
      spec: clang@12.0.1
      target: x86_64

  config:
    build_jobs: 2

  mirrors:
    E4S: https://cache.e4s.io
