# This is a Spack environment file.
#
# Activating and installing this environment will provide all dependencies
# that are needed for full-feature development.
#   https//spack.readthedocs.io/en/latest/environments.html#anonymous-environments
#
spack:
  specs:
  - adios2@2.10 +mpi
  - hdf5 +mpi
  - mpich

  packages:
    adios2:
      variants: +mpi ~zfp ~sz ~png ~dataman ~python ~fortran ~ssc ~shared ~bzip2 ~blosc2 ~mgard
    cmake:
      externals:
      - spec: cmake@3.31.6
        prefix: /usr/local
      buildable: False
    hdf5:
      variants: +mpi
    mpich:
      externals:
      - spec: mpich@4.2.0
        prefix: /usr
      buildable: False
    perl:
      externals:
      - spec: perl@5.38.2
        prefix: /usr
      buildable: False
    python:
      externals:
      - spec: python@3.12.3
        prefix: /usr
      buildable: False
    all:
      target: [x86_64]
      variants: ~fortran
      providers:
        mpi: [mpich]
      compiler: [gcc@13.3.0]

  compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: ubuntu24.04
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@13.3.0
      target: x86_64

  config:
    build_jobs: 4

  mirrors:
    E4S: https://cache.e4s.io
