
["$defs"]

######################
# Vectors of strings #
######################

[["$defs".vec_string_attribute.oneOf]]
title = "Shorthand notation"
anyOf = [
    { type = "string" },
    { type = "array", items = { "type" = "string" } },
]

[["$defs".vec_string_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".vec_string_attribute.oneOf.properties]

value.anyOf = [
    { type = "string" },
    { type = "array", items = { "type" = "string" } },
]

datatype.enum = [
    "STRING",
    "CHAR",
    "SCHAR",
    "UCHAR",
    "VEC_STRING",
    "VEC_CHAR",
    "VEC_SCHAR",
    "VEC_UCHAR",
]

##################
# Vectors of int #
##################

[["$defs".vec_int_attribute.oneOf]]
title = "Shorthand notation"
anyOf = [
    { type = "integer" },
    { type = "array", items = { "type" = "integer" } },
]

[["$defs".vec_int_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".vec_int_attribute.oneOf.properties]

value.anyOf = [
    { type = "integer" },
    { type = "array", items = { "type" = "integer" } },
]

datatype.enum = [
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
    "VEC_SHORT",
    "VEC_INT",
    "VEC_LONG",
    "VEC_LONGLONG",
    "VEC_USHORT",
    "VEC_UINT",
    "VEC_ULONG",
    "VEC_ULONGLONG",
]

####################
# Vectors of float #
####################

[["$defs".vec_float_attribute.oneOf]]
title = "Shorthand notation"
anyOf = [
    { type = "number" },
    { type = "array", items = { "type" = "number" } },
]

[["$defs".vec_float_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".vec_float_attribute.oneOf.properties]

value.anyOf = [
    { type = "number" },
    { type = "array", items = { "type" = "number" } },
]

datatype.enum = [
    "CHAR",
    "UCHAR",
    "SCHAR",
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
    "FLOAT",
    "DOUBLE",
    "LONG_DOUBLE",
    "CFLOAT",
    "CDOUBLE",
    "CLONG_DOUBLE",
    "VEC_SHORT",
    "VEC_INT",
    "VEC_LONG",
    "VEC_LONGLONG",
    "VEC_USHORT",
    "VEC_UINT",
    "VEC_ULONG",
    "VEC_ULONGLONG",
    "VEC_FLOAT",
    "VEC_DOUBLE",
    "VEC_LONG_DOUBLE",
    "VEC_CFLOAT",
    "VEC_CDOUBLE",
    "VEC_CLONG_DOUBLE",
]

###########################
# Special case:           #
# unitDimension attribute #
###########################

[["$defs".unitDimension.oneOf]]
title = "Shorthand notation"
type = "array"
items.type = "number"

[["$defs".unitDimension.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".unitDimension.oneOf.properties]

value = { type = "array", items = { type = "number" } }
datatype.const = "ARR_DBL_7"

#####################
# string attributes #
#####################

[["$defs".string_attribute.oneOf]]
title = "Shorthand notation"
type = "string"

[["$defs".string_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".string_attribute.oneOf.properties]

value.type = "string"
datatype.enum = ["STRING", "CHAR", "SCHAR", "UCHAR"]

##################
# int attributes #
##################

[["$defs".int_attribute.oneOf]]
title = "Shorthand notation"
type = "integer"

[["$defs".int_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".int_attribute.oneOf.properties]

value.type = "integer"
datatype.enum = [
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
]

####################
# float attributes #
####################

[["$defs".float_attribute.oneOf]]
title = "Shorthand notation"
type = "number"

[["$defs".float_attribute.oneOf]]
title = "Long notation"
type = "object"
required = ["value", "datatype"]

["$defs".float_attribute.oneOf.properties]

value.type = "number"
datatype.enum = [
    "CHAR",
    "UCHAR",
    "SCHAR",
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
    "FLOAT",
    "DOUBLE",
    "LONG_DOUBLE",
    "CFLOAT",
    "CDOUBLE",
    "CLONG_DOUBLE",
]
