["$defs"]

######################################
# n-dimensional datasets of any type #
######################################

[["$defs".any_type_recursive_array.anyOf]]
title = "A numeric type"
type = "array"
items.anyOf = [{ "type" = "number" }, { "type" = "null" }]

[["$defs".any_type_recursive_array.anyOf]]
title = "A recursive array of numeric types"
type = "array"
items."$ref" = "#/$defs/any_type_recursive_array"


["$defs".any_type_dataset_properties.properties]
datatype.enum = [
    "CHAR",
    "UCHAR",
    "SCHAR",
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
    "FLOAT",
    "DOUBLE",
    "LONG_DOUBLE",
    "CFLOAT",
    "CDOUBLE",
    "CLONG_DOUBLE",
    "BOOL",
]
data."$ref" = "#/$defs/any_type_recursive_array"
extent = { type = "array", items = { type = "integer" } }


###################################################
# Either `datatype` and `data` must be defined... #
###################################################

[["$defs".any_type_dataset.anyOf]]
title = "A dataset of any numeric type"
allOf = [
    { required = [
        "datatype",
        "data",
    ], title = "Required properties" },
    { "$ref" = "#/$defs/any_type_dataset_properties", title = "Property definitions" },
]

#########################################################
# ...or `datatype` and `extent` must be (template form) #
#########################################################

[["$defs".any_type_dataset.anyOf]]
title = "A template dataset of any numeric type"
allOf = [
    { required = [
        "datatype",
        "extent",
    ], title = "Required properties" },
    { "$ref" = "#/$defs/any_type_dataset_properties", title = "Property definitions" },
]

######################################
# n-dimensional datasets of int type #
######################################

[["$defs".int_type_recursive_array.anyOf]]
title = "An integer type"
type = "array"
items.anyOf = [{ "type" = "integer" }, { "type" = "null" }]

[["$defs".int_type_recursive_array.anyOf]]
title = "A recursive array of integer types"
type = "array"
items."$ref" = "#/$defs/int_type_recursive_array"


["$defs".int_type_dataset_properties.properties]
datatype.enum = [
    "CHAR",
    "UCHAR",
    "SCHAR",
    "SHORT",
    "INT",
    "LONG",
    "LONGLONG",
    "USHORT",
    "UINT",
    "ULONG",
    "ULONGLONG",
    "BOOL",
]
data."$ref" = "#/$defs/int_type_recursive_array"
extent = { type = "array", items = { type = "integer" } }


###################################################
# Either `datatype` and `data` must be defined... #
###################################################

[["$defs".int_type_dataset.anyOf]]
title = "A dataset of integer type"
allOf = [
    { required = [
        "datatype",
        "data",
    ], title = "Required properties" },
    { "$ref" = "#/$defs/int_type_dataset_properties", title = "Property definitions" },
]

#########################################################
# ...or `datatype` and `extent` must be (template form) #
#########################################################

[["$defs".int_type_dataset.anyOf]]
title = "A dataset template of integer type"
allOf = [
    { required = [
        "datatype",
        "extent",
    ], title = "Required properties" },
    { "$ref" = "#/$defs/int_type_dataset_properties", title = "Property definitions" },
]
