#########################################################
# Requirement 1: Mesh-specific structure and attributes #
#########################################################

[[allOf]]

type = "object"
required = ["attributes"]
title = "Record"
description = "A list of particle quantities."

[allOf.properties.attributes]
title = "Attributes"

####################################
# Requirement 1.1: Mesh attributes #
####################################

[[allOf.properties.attributes.allOf]]

title = "Particle Record attributes"
description = "Standard-defined attributes at the Particle Record level."
required = ["timeOffset", "unitDimension"]

[allOf.properties.attributes.allOf.properties]

timeOffset."$ref" = "attribute_defs.json#/$defs/float_attribute"
unitDimension."$ref" = "attribute_defs.json#/$defs/unitDimension"
dataOrder."$ref" = "attribute_defs.json#/$defs/string_attribute"

################################################
# Requirement 1.2: Generic attribute structure #
################################################

[[allOf.properties.attributes.allOf]]
title = "Attribute layout"
"$ref" = "attributes.json"

######################################
# Requirement 2: Contains components #
######################################

[[allOf]]
title = "Contains components"

####################################################
# Requirement 2.1: Either this is a scalar mesh... #
####################################################

[[allOf.oneOf]]
title = "Scalar component"
"$ref" = "record_component.json"

#################################################
# Requirement 2.2: ... or it's a vector mesh.   #
# Note that exactly one of these two conditions #
# must be true, not both at once (oneOf).       #
#################################################

[[allOf.oneOf]]
title = "Vector component"
description = "Additionally to the attributes, at least one component must be contained"
# The attributes are contained in this dict, and at least one further
# non-scalar component. Hence, we require at least two entries.
minProperties = 2
propertyNames.pattern = "^\\w*$"

[allOf.oneOf.patternProperties]

[allOf.oneOf.patternProperties."^(?!attributes).*"]
title = "Scalar component"
"$ref" = "record_component.json"
