# This is a Spack environment file.
#
# Activating and installing this environment will provide all dependencies
# that are needed for full-feature development.
#   https//spack.readthedocs.io/en/latest/environments.html#anonymous-environments
#
spack:
  specs:
  - adios2@2.10
  - hdf5
  - openmpi
  - py-h5py

  packages:
    adios2:
      variants: ~zfp ~sz ~png ~dataman ~python ~fortran ~ssc ~shared ~bzip2 ~mgard

    c-blosc2:
      # snappy broken on CMake 4.0
      # fixed snappy not yet deployed to a Spack release
      variants: ~snappy

    cmake:
      externals:
      - spec: cmake@3.31.8
        prefix: /usr/local
      buildable: False

    openmpi:
      externals:
      - spec: openmpi@4.1.6
        prefix: /usr
      buildable: False

    perl:
      externals:
      - spec: perl@5.38.2
        prefix: /usr
      buildable: False

    python:
      externals:
      - spec: python@3.12.3
        prefix: /usr
      buildable: False

    all:
      target: [x86_64]
      variants: ~fortran
      providers:
        mpi: [openmpi]
        cc: [llvm]
        cxx: [llvm]
        fortran: [gcc]

    llvm:
      externals:
      - spec: llvm@19.1.1
        prefix: /usr
        paths:
          cc: /usr/bin/clang-19
          cxx: /usr/bin/clang++-19
        modules: []
        environment: {}
        extra_rpaths: []
      buildable: False

    gcc:
      externals:
      - spec: gcc@13.3.0
        prefix: /usr
        paths:
          cc: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
        modules: []
        environment: {}
        extra_rpaths: []
      buildable: False

    gcc-runtime:
      buildable: false
      externals:
        - spec: gcc-runtime@13.3.0
          prefix: /usr

  config:
    build_jobs: 2

  mirrors:
    spack-public: https://mirror.spack.io
