#!/usr/bin/env bash
#

set -eu -o pipefail

spack_ver="2b6f896ca744081a38579573a52824bf334fb54b"

cd /opt
if [[ -d spack && ! -f spack_${spack_ver} ]]
then
    rm -rf spack /usr/bin/spack $HOME/.spack/
fi
if [ ! -d spack ]
then
  # download
  curl -sOL https://github.com/spack/spack/archive/${spack_ver}.tar.gz
  tar -xf ${spack_ver}.tar.gz && rm ${spack_ver}.tar.gz
  mv spack-${spack_ver} spack
  touch spack_${spack_ver}
fi

# install
ln -s /opt/spack/bin/spack /usr/bin/spack

# add binary mirror
spack mirror add E4S https://cache.e4s.io
curl -sOL https://oaciss.uoregon.edu/e4s/e4s.pub
spack gpg trust e4s.pub

# find compilers & external packages
spack compiler find
#spack external find

# accessible by regular CI user
chmod a+rwx -R /opt/spack
chmod a+rwx $HOME/.spack/
