#!/usr/bin/env bash

set -eu -o pipefail
set -x

cd /opt

version="v2.0.0"
patch_url="https://github.com/franzpoeschel/HDF5-Blosc2/commit/55b1feea7bf18a539dfbe4413a920bc9570aa0c6.patch"
patch_path="$(pwd)/hdf5_blosc2_cmake_fixes.patch"


curl -sLo "$patch_path" "$patch_url"
git clone -b "$version" https://github.com/Blosc/HDF5-Blosc2
cd HDF5-Blosc2
git config user.email "tooling@tools.com"
git config user.name "Tooling"
git am "$patch_path"

cmake . -B build -DCMAKE_INSTALL_PREFIX="/usr/local" -DBUILD_TESTS=OFF
cmake --build build --parallel 4
sudo cmake --build build --parallel 4 --target install
